redis:
  image: redis
db:
  image: postgres
  environment:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
vote:
  image: vote
  ports:
    - 1000:80
  links:
    - redis
worker:
  image: worker
  links:
    - redis
    - db
result:
  image: result
  ports:
    - 1001:80
  links:
    - db
